AWSTemplateFormatVersion: '2010-09-09'
Description: 'DataSurface - IAM Roles for EKS Service Accounts (IRSA)'

Parameters:
  EKSOIDCProviderArn:
    Type: String
    Description: The ARN of the EKS OIDC Identity Provider.
  StackName:
    Type: String
    Description: The name of the main EKS stack to associate with these roles.

# NOTE: OIDC scope conditions cannot be set here because CloudFormation does not
# support intrinsic functions (!Sub) as YAML mapping keys. The roles are created
# without scope conditions, then Step 3 of the setup-walkthrough-aws skill applies
# the correctly scoped trust policies via AWS CLI. Do NOT skip Step 3.

Resources:
  EFSCSIDriverRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref EKSOIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
      Policies:
        - PolicyName: EFSCSIDriverPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:DescribeAccessPoints
                  - elasticfilesystem:DescribeFileSystems
                  - elasticfilesystem:DescribeMountTargets
                  - elasticfilesystem:CreateAccessPoint
                  - elasticfilesystem:DeleteAccessPoint
                  - elasticfilesystem:TagResource
                  - elasticfilesystem:UntagResource
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "${StackName}-efs-csi-driver-role"

  AirflowSecretsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref EKSOIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Tags:
        - Key: Name
          Value: !Sub "${StackName}-airflow-secrets-role"

Outputs:
  EFSCSIDriverRoleArn:
    Description: IAM Role ARN for EFS CSI Driver (for IRSA)
    Value: !GetAtt EFSCSIDriverRole.Arn
    Export:
      Name: !Sub "${StackName}-EFS-CSI-Driver-Role-Arn"

  AirflowSecretsRoleArn:
    Description: IAM Role ARN for Airflow Secrets Manager access (for IRSA)
    Value: !GetAtt AirflowSecretsRole.Arn
    Export:
      Name: !Sub "${StackName}-Airflow-Secrets-Role-Arn"
